language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng build --prod --base-href /smarthome-dashboard
- mv dist/smarthome-dashboard/index.html dist/smarthome-dashboard/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/my-awesome-project
  on:
    branch: master