language: node_js
node_js:
  - "10.9"
dist: trusty
sudo: required
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_script:
  - npm install -g @angular/cli
script:
- ng build --prod --output-path docs --base-href /smarthome-dashboard/
- mv docs/index.html docs/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/smarthome-dashboard/
  on:
    branch: master